version: '3'
services:
  postgres:
    image: postgres:13
    container_name: app-db
    hostname: app-db
    env_file:
      - test.env
    ports:
      - "5432:5432"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app/
    working_dir: /usr/src/app/
    entrypoint: ["make", 'server-docker']
    environment:
      - APP_CONFIG_FILE=../config/development.py
    ports:
      - "5000:5000"
    depends_on:
      - postgres        
